services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    networks: 
      - social-media-network
    env_file:
      - ./secrets/.env.api
    depends_on:
      db: 
        condition: service_healthy
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - social-media-network
    env_file:
      - ./secrets/.env.web
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    networks:
      - social-media-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  social-media-network:
